-- CRIAÇÃO DO USUÁRIO
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_ID_USUARIO INCREMENT BY 1 START WITH 1;
*/
INSERT INTO t_fin_cadastro (ID_USUARIO,TX_LOGIN,TX_SENHA,NR_CPF,NM_USUARIO,tx_email,nr_telefone,dt_nascimento,tx_genero)
VALUES (SQ_ID_USUARIO.NEXTVAL,'roger.teste','123456','36280868842','Roger','roger.teste@fiap.com.br','1144444444',TO_DATE('19890815','YYYYMMDD'),'M');
INSERT INTO t_fin_cadastro (ID_USUARIO,TX_LOGIN,TX_SENHA,NR_CPF,NM_USUARIO,tx_email,nr_telefone,dt_nascimento,tx_genero)
VALUES (SQ_ID_USUARIO.NEXTVAL,'felipe.teste','1234567','99999999999','Felipe','felipe.teste@fiap.com.br','1144444444',TO_DATE('19950101','YYYYMMDD'),'M');
INSERT INTO t_fin_cadastro (ID_USUARIO,TX_LOGIN,TX_SENHA,NR_CPF,NM_USUARIO,tx_email,nr_telefone,dt_nascimento,tx_genero)
VALUES (SQ_ID_USUARIO.NEXTVAL,'vitor.teste','1234567','99999999999','Vitor','vitor.teste@fiap.com.br','1144444444',TO_DATE('19961214','YYYYMMDD'),'M');
INSERT INTO t_fin_cadastro (ID_USUARIO,TX_LOGIN,TX_SENHA,NR_CPF,NM_USUARIO,tx_email,nr_telefone,dt_nascimento,tx_genero)
VALUES (SQ_ID_USUARIO.NEXTVAL,'lucas.teste','1234567','99999999999','Lucas','lucas.teste@fiap.com.br','1144444444',TO_DATE('19930510','YYYYMMDD'),'M');

-- ALTERAÇÃO DADOS DO USUÁRIO FILTRANDO NO LOGIN E NO ID
UPDATE t_fin_cadastro SET TX_EMAIL='roger.update@fiap.com.br',nr_telefone='1155555555' where TX_LOGIN='roger.teste';
UPDATE t_fin_cadastro SET TX_EMAIL='felipe.update@fiap.com.br',nr_telefone='1199999999' where TX_LOGIN='felipe.teste';
UPDATE t_fin_cadastro SET NR_CPF='12345678901' ,nr_telefone='1388999999' where ID_USUARIO=22;


--CADASTRO TIPO DESPESA
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_ID_TP_DESPESA INCREMENT BY 1 START WITH 1;
*/
INSERT INTO t_fin_tipo_despesa (cod_despesa,ds_despesa) VALUES(SQ_ID_TP_DESPESA.NEXTVAL,'DESPESAS FIXAS');
INSERT INTO t_fin_tipo_despesa (cod_despesa,ds_despesa) VALUES(SQ_ID_TP_DESPESA.NEXTVAL,'DESPESAS VARIÁVEIS');
INSERT INTO t_fin_tipo_despesa (cod_despesa,ds_despesa) VALUES(SQ_ID_TP_DESPESA.NEXTVAL,'BOLETO');

--CADASTRO DESPESA 
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_ID_DESPESA INCREMENT BY 1 START WITH 1;
*/
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230418','YYYYMMDD'),'CARTAO DE CREDITO',100,0,'',1,1);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230419','YYYYMMDD'),'PIX',1000,0,'',1,1);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230118','YYYYMMDD'),'GÁS',500.50,0,'',1,3);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230218','YYYYMMDD'),'ENEL',150.56,0,'',1,2);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230419','YYYYMMDD'),'PIX PARA JOSE',1350.35,0,'',22,1);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230319','YYYYMMDD'),'SABESP',76.87,0,'',22,1);
INSERT INTO T_FIN_DESPESA (ID_DESPESA,DT_DESPESA,DS_DESPESA,VL_DESPESA,QTD_MES_RECORRENCIA,ST_RECORRENCIA,t_fin_cadastro_id_usuario,t_fin_tipo_despesa_cod_despesa)
VALUES (SQ_ID_DESPESA.NEXTVAL,TO_DATE('20230319','YYYYMMDD'),'FIAP - ADS',1138.98,0,'',21,1);
--CADASTRO TIPO DE RECEITA
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_ID_TP_RECEITA INCREMENT BY 1 START WITH 1;
*/
INSERT INTO t_fin_tipo_receita (cod_receita,ds_receita) VALUES(SQ_ID_TP_RECEITA.NEXTVAL,'SALARIO');
INSERT INTO t_fin_tipo_receita (cod_receita,ds_receita) VALUES(SQ_ID_TP_RECEITA.NEXTVAL,'PIX RECEBIDO');
INSERT INTO t_fin_tipo_receita (cod_receita,ds_receita) VALUES(SQ_ID_TP_RECEITA.NEXTVAL,'DEPOSITO');
INSERT INTO t_fin_tipo_receita (cod_receita,ds_receita) VALUES(SQ_ID_TP_RECEITA.NEXTVAL,'TRANSFERENCIA');

--CADASTRO DE RECEITAS
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_ID_RECEITA INCREMENT BY 1 START WITH 1;
*/
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'SALARIO ANTECIPADO',4500.35,TO_DATE('20230419','YYYYMMDD'),1,1);
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'PIX JOAO',200,TO_DATE('20230402','YYYYMMDD'),1,1);
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'SALARIO JANEIRO',9000.10,TO_DATE('20230205','YYYYMMDD'),1,2);
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'SALARIO JANEIRO',9000.10,TO_DATE('20230205','YYYYMMDD'),2,2);
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'SALARIO DEZEMBRO',7678.65,TO_DATE('20230105','YYYYMMDD'),21,2);
INSERT INTO T_FIN_RECEITA (ID_RECEITA,DS_RECEITA,VL_RECEITA,DT_RECEITA,T_FIN_CADASTRO_ID_USUARIO,T_FIN_TIPO_RECEITA_COD_RECEITA)
VALUES (SQ_ID_RECEITA.NEXTVAL,'PIX RECEBIDO',9000.10,TO_DATE('20230401','YYYYMMDD'),21,2);

--ALTERAÇÃO DAS RECEITAS
UPDATE T_FIN_RECEITA SET DS_RECEITA='FÉRIAS',VL_RECEITA=7500,DT_RECEITA=TO_DATE('20230418','YYYYMMDD') WHERE ID_RECEITA=2;
UPDATE T_FIN_RECEITA SET DS_RECEITA='PIX JOHN',DT_RECEITA=TO_DATE('20230415','YYYYMMDD') WHERE ID_RECEITA=3;
UPDATE T_FIN_RECEITA SET T_FIN_TIPO_RECEITA_COD_RECEITA=1 WHERE ID_RECEITA=5;


--CADASTRO CARTÃO
/* SEQUENCIA CADASTRADA
CREATE SEQUENCE SQ_TP_CARTAO INCREMENT BY 1 START WITH 1;
*/
INSERT INTO  t_cartao VALUES 
	(SQ_TP_CARTAO.NEXTVAL, 'cartao do fulano', '1234234534565678', TO_DATE('202901','YYYYMM'), 'master', '456', 'credito', 
	'40161920808', 1 );

INSERT INTO  t_cartao VALUES 
	(SQ_TP_CARTAO.NEXTVAL, 'cartao do siclano', '1234798454565678', TO_DATE('202901','YYYYMM'), 'super', '486', 'debito', 
	'40798456808', 2 );

-- ALTERAÇÃO CARTAO
UPDATE t_cartao
SET 	nm_cartao = 'cartones', 
	nr_cartao = '1234797854565678', 
	dsc_bandeira_cartao = 'hiper', 
	nr_cvv_cartao = '486',  
	dsc_tipo_cartao = 'debito',
	nr_cpf_titular_cartao = '40798478808'       
WHERE cd_cartao = 3;

UPDATE t_cartao
SET 	nm_cartao = 'pagamentos', 
	nr_cartao = '1234797984565678', 
	dsc_bandeira_cartao = 'mega', 
	nr_cvv_cartao = '886',  
	dsc_tipo_cartao = 'credito',
	nr_cpf_titular_cartao = '40791238808'       
WHERE cd_cartao = 4;


--SELECTS DE CONSULTA
--USUARIO X CARTÕES FILTRADO NO USUÁRIO roger.teste
SELECT 
A.NR_CPF NR_CPF,
A.NM_USUARIO NM_USUARIO,
T.CD_CARTAO CD_CARTAO,
T.NM_CARTAO NM_CARTAO,
T.NR_CARTAO NR_CARTAO,
T.DT_VALIDADE_CARTAO DT_VALIDADE_CARTAO,
T.DSC_BANDEIRA_CARTAO DSC_BANDEIRA_CARTAO,
T.NR_CVV_CARTAO NR_CVV_CARTAO,
T.DSC_TIPO_CARTAO DSC_TIPO_CARTAO,
T.NR_CPF_TITULAR_CARTAO NR_CPF_TITULAR_CARTAO,
T.T_FIN_CADASTRO_ID_USUARIO T_FIN_CADASTRO_ID_USUARIO FROM t_fin_cadastro A
INNER JOIN t_cartao T ON A.ID_USUARIO=T.T_FIN_CADASTRO_ID_USUARIO
 WHERE TX_LOGIN='roger.teste';
 
 --USUÁRIO X DESPESAS FILTRADOS NO USUÁRIO roger.teste DAS MAIS RECENTES PARA ANTIGAS
 SELECT ID_USUARIO,TX_LOGIN,DT_DESPESA,D.DS_DESPESA AS DESCRICAO_DA_DESPESA,VL_DESPESA,T.DS_DESPESA AS DESCRICAO_TIPO_DESPESA FROM t_fin_cadastro A
INNER JOIN T_FIN_DESPESA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
INNER JOIN t_fin_tipo_despesa T ON T.cod_despesa=t_fin_tipo_despesa_cod_despesa
 WHERE TX_LOGIN='roger.teste'
 ORDER BY DT_DESPESA DESC;
 
 --CONSULTA DE USUÁRIO POR CODIGO E RECEITA POR CODIGO
  SELECT A.ID_USUARIO ID_USUARIO,
A.TX_LOGIN TX_LOGIN,
A.NR_CPF NR_CPF,
A.NM_USUARIO NM_USUARIO,
A.TX_EMAIL TX_EMAIL,
D.ID_RECEITA ID_RECEITA,
D.DS_RECEITA DS_RECEITA,
D.VL_RECEITA VL_RECEITA,
D.DT_RECEITA DT_RECEITA,
D.T_FIN_CADASTRO_ID_USUARIO T_FIN_CADASTRO_ID_USUARIO,
D.T_FIN_TIPO_RECEITA_COD_RECEITA T_FIN_TIPO_RECEITA_COD_RECEITA
,E.DS_RECEITA AS TIPO_RECEITA
 FROM t_fin_cadastro A
INNER JOIN T_FIN_RECEITA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
INNER JOIN T_FIN_TIPO_RECEITA E ON E.cod_receita=D.T_FIN_TIPO_RECEITA_COD_RECEITA
WHERE ID_USUARIO=1 AND ID_RECEITA=2;

 -- USUÁRIO X ULTIMA DESPESA
SELECT ID_USUARIO,TX_LOGIN,DT_DESPESA,D.DS_DESPESA AS DESCRICAO_DA_DESPESA,VL_DESPESA,T.DS_DESPESA AS DESCRICAO_TIPO_DESPESA FROM t_fin_cadastro A
INNER JOIN T_FIN_DESPESA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
INNER JOIN t_fin_tipo_despesa T ON T.cod_despesa=t_fin_tipo_despesa_cod_despesa
WHERE TX_LOGIN='roger.teste' AND D.DT_DESPESA IN (SELECT MAX(DT_DESPESA) FROM T_FIN_DESPESA H WHERE H.T_FIN_CADASTRO_ID_USUARIO=ID_USUARIO  );

-- TOTAL DE DESPESAS GERAL X  USUÁRIO (TODOS OS USUÁRIOS) - UTILIZAÇÃO INTERNA
 SELECT ID_USUARIO,TX_LOGIN,SUM(VL_DESPESA) AS TOTAL_DESPESA_GERAL
 FROM t_fin_cadastro A
INNER JOIN T_FIN_DESPESA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
GROUP BY A.ID_USUARIO,A.TX_LOGIN
ORDER BY A.ID_USUARIO ;

---- TOTAL DE RECEITA GERAL X  USUÁRIO
 SELECT ID_USUARIO,TX_LOGIN,SUM(VL_RECEITA) AS TOTAL_RECEITA_GERAL
 FROM t_fin_cadastro A
INNER JOIN T_FIN_RECEITA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
WHERE ID_USUARIO=21
GROUP BY A.ID_USUARIO,A.TX_LOGIN ;

--DADOS BASICOS DO USUÁRIO X ULTIMA RECEITA X ULTIMA DESPESA
--USUARIO roger.teste
SELECT ID_USUARIO,TX_LOGIN,DT_DESPESA,D.DS_DESPESA AS DESCRICAO_DA_DESPESA,VL_DESPESA,T.DS_DESPESA AS DESCRICAO_TIPO_DESPESA
,DT_RECEITA,VL_RECEITA,DS_RECEITA FROM t_fin_cadastro A
INNER JOIN T_FIN_DESPESA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
INNER JOIN t_fin_tipo_despesa T ON T.cod_despesa=t_fin_tipo_despesa_cod_despesa
INNER JOIN T_FIN_RECEITA E ON A.ID_USUARIO=E.t_fin_cadastro_id_usuario
WHERE TX_LOGIN='roger.teste' AND D.DT_DESPESA IN (SELECT MAX(DT_DESPESA) FROM T_FIN_DESPESA H WHERE H.T_FIN_CADASTRO_ID_USUARIO=ID_USUARIO  )
AND E.DT_RECEITA IN (SELECT MAX(DT_RECEITA) FROM T_FIN_RECEITA G WHERE G.T_FIN_CADASTRO_ID_USUARIO=ID_USUARIO  );

--usuario vitor.teste
SELECT ID_USUARIO,TX_LOGIN,DT_DESPESA,D.DS_DESPESA AS DESCRICAO_DA_DESPESA,VL_DESPESA,T.DS_DESPESA AS DESCRICAO_TIPO_DESPESA
,DT_RECEITA,VL_RECEITA,DS_RECEITA FROM t_fin_cadastro A
INNER JOIN T_FIN_DESPESA D ON A.ID_USUARIO=D.t_fin_cadastro_id_usuario
INNER JOIN t_fin_tipo_despesa T ON T.cod_despesa=t_fin_tipo_despesa_cod_despesa
INNER JOIN T_FIN_RECEITA E ON A.ID_USUARIO=E.t_fin_cadastro_id_usuario
WHERE TX_LOGIN='vitor.teste' AND D.DT_DESPESA IN (SELECT MAX(DT_DESPESA) FROM T_FIN_DESPESA H WHERE H.T_FIN_CADASTRO_ID_USUARIO=ID_USUARIO  )
AND E.DT_RECEITA IN (SELECT MAX(DT_RECEITA) FROM T_FIN_RECEITA G WHERE G.T_FIN_CADASTRO_ID_USUARIO=ID_USUARIO  );




 
 
 
 


